classDiagram
class ClassName {
    +AttributeType attributeName
    +MethodType methodName()
}
ClassName1 --|> ClassName2 : Inheritance
ClassName3 o-- ClassName : Composition
ClassName4 --> ClassName : Association